<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List</title>
    <link rel="stylesheet" href="css/common.css">
    <link rel="icon" type="image/x-icon" href="css/cubs.png">
</head>
<body>
<div id="nav-placeholder"></div>

<main>
    <div style="margin-top: 40px">
        <div style="text-align: -webkit-center; display: grid;">
        <span class="normalFont" style="font-size: 16px; color: white; margin-top: 15px;">Home > <span
                    style="color: #FA9021">News</span></span>
            <span class="boldFont" style="font-size: 33px; color: white; margin-top: 15px;">Lorem Ipsum is simply dummy text of the printing and.</span>
            <span class="normalFont" style="font-size: 16px; color: white; margin-top: 15px;">Lorem Ipsum is simply dummy text of the printing and.</span>
        </div>
        <#--        List is started-->
        <div style="margin-left: 300px; margin-right: 240px; margin-top: 90px">

            <div>
            <span style="display: inline-flex">
                <img src="css/ex1.png" class="item-list" style="width: 192px; height: 192px">
                <span style="margin-left: 30px; display: block; padding-top: 30px; padding-bottom: 30px">
                    <div>
                        <span style="background: #FF8484; padding: 8px 26px; color: white; font-size: 14px"
                              class="normalFont">John smash</span>
                        <span class="normalFont" style="font-size: 14px; color: white; margin-left: 16px">.5min</span>
                    </div>
                    <div class="normalFont"
                         style="color: white; font-size: 23px; font-weight: 510; width: 300px; margin-top: 20px">
                        Lorem Ipsum is simply dummy text dummy text?
                    </div>
                </span>
            </span>

                <span style="display: inline-flex; margin-left: 70px">
                <img src="css/ex1.png" class="item-list" style="width: 192px; height: 192px">
                <span style="margin-left: 30px; display: block; padding-top: 30px; padding-bottom: 30px">
                    <div>
                        <span style="background: #FF8484; padding: 8px 26px; color: white; font-size: 14px"
                              class="normalFont">John smash</span>
                        <span class="normalFont" style="font-size: 14px; color: white; margin-left: 16px">.5min</span>
                    </div>
                    <div class="normalFont"
                         style="color: white; font-size: 23px; font-weight: 510; width: 300px; margin-top: 20px">
                        Lorem Ipsum is simply dummy text dummy text?
                    </div>
                </span>
            </span>

            </div>

            <div>

            <span style="display: inline-flex">
                <img src="css/ex1.png" class="item-list" style="width: 192px; height: 192px">
                <span style="margin-left: 30px; display: block; padding-top: 30px; padding-bottom: 30px">
                    <div>
                        <span style="background: #2351F5; padding: 8px 26px; color: white; font-size: 14px"
                              class="normalFont">John smash</span>
                        <span class="normalFont" style="font-size: 14px; color: white; margin-left: 16px">.5min</span>
                    </div>
                    <div class="normalFont"
                         style="color: white; font-size: 23px; font-weight: 510; width: 300px; margin-top: 20px">
                        Lorem Ipsum is simply dummy text dummy text?
                    </div>
                </span>
            </span>

                <span style="display: inline-flex; margin-left: 70px">
                <img src="css/ex1.png" class="item-list" style="width: 192px; height: 192px">
                <span style="margin-left: 30px; display: block; padding-top: 30px; padding-bottom: 30px">
                    <div>
                        <span style="background: #2351F5; padding: 8px 26px; color: white; font-size: 14px"
                              class="normalFont">John smash</span>
                        <span class="normalFont" style="font-size: 14px; color: white; margin-left: 16px">.5min</span>
                    </div>
                    <div class="normalFont"
                         style="color: white; font-size: 23px; font-weight: 510; width: 300px; margin-top: 20px">
                        Lorem Ipsum is simply dummy text dummy text?
                    </div>
                </span>
            </span>

            </div>

            <div>

            <span style="display: inline-flex">
                <img src="css/ex1.png" class="item-list" style="width: 192px; height: 192px">
                <span style="margin-left: 30px; display: block; padding-top: 30px; padding-bottom: 30px">
                    <div>
                        <span style="background: #FF7C32; padding: 8px 26px; color: white; font-size: 14px"
                              class="normalFont">John smash</span>
                        <span class="normalFont" style="font-size: 14px; color: white; margin-left: 16px">.5min</span>
                    </div>
                    <div class="normalFont"
                         style="color: white; font-size: 23px; font-weight: 510; width: 300px; margin-top: 20px">
                        Lorem Ipsum is simply dummy text dummy text?
                    </div>
                </span>
            </span>

                <span style="display: inline-flex; margin-left: 70px">
                <img src="css/ex1.png" class="item-list" style="width: 192px; height: 192px">
                <span style="margin-left: 30px; display: block; padding-top: 30px; padding-bottom: 30px">
                    <div>
                        <span style="background: #FF7C32; padding: 8px 26px; color: white; font-size: 14px"
                              class="normalFont">John smash</span>
                        <span class="normalFont" style="font-size: 14px; color: white; margin-left: 16px">.5min</span>
                    </div>
                    <div class="normalFont"
                         style="color: white; font-size: 23px; font-weight: 510; width: 300px; margin-top: 20px">
                        Lorem Ipsum is simply dummy text dummy text?
                    </div>
                </span>
            </span>

            </div>

        </div>
        <#--        List is ended-->
    </div>
</main>

<footer style="background: black; padding-top: 73px; padding-bottom: 30px; color: white">

    <div style="display: inline-flex; padding-left: 100px; padding-right: 100px">
        <div style="width: 372px;">
            <span class="boldFont" style="font-size: 24pt">RANDOMITY</span><br><br>
            <span class="normalFont" style="color: white; font-size: 16px;">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</span><br><br><br>
            <span class="normalFont" style="color: white; font-size: 16px; margin-top: 25px;">@Logo</span>
        </div>

        <div class="normalFont" style="margin-left: 78px; text-decoration: none; line-height: 2">
            <span style="font-weight: 600">About us</span><br><br>
            <a href="/">Zeux</a><br>
            <a href="/">Portfolio</a><br>
            <a href="/">Careers</a><br>
            <a href="/">Contact us</a>
        </div>

        <div class="normalFont" style="margin-left: 78px;
    color: white; line-height: 2">
            <span style="font-weight: 600">Contact us</span><br><br>
            <a href="/">Блабла</a><br>
            <span>+927 818 33 41</span>
        </div>

        <div style="margin-top: 150px; margin-left: 160px">
            <img src="css/facebook_icon.png">
            <img style="margin-left: -15px;" src="css/inst_icon.png">
            <img style="margin-left: -15px;" src="css/twitter_icon.png">
            <img style="margin-left: -15px;" src="css/in_icon.png">
        </div>

    </div>

    <hr style="color: white">

    <span class="normalFont" style="display:block; text-align: -webkit-center;">Copyright ® 2022 Lorem All rights Reserved</span>
</footer>

</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    $(function () {
        <#if isGuest>
        $("#nav-placeholder").load("templates/guest_nav.html");
        <#else>
        $("#nav-placeholder").load("templates/user_nav.html");
        </#if>
    });
</script>
</html>