server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: https://184732:eyJrIjoiZTBhN2YxMDFjNDQxMTU0NzllYWVhMDM3NTI1NDNmOWIwNzcyMmQ0YyIsIm4iOiJyYW5kb21pdHktc2VydmVyIiwiaWQiOjYyMDUyN30=@logs-prod-eu-west-0.grafana.net/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: monitoring-demo
          __path__: /var/log/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
      - labels:
          level:
