server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: https://184732:eyJrIjoiYWFkZDhiMGM4Y2VkYjBkYTA3MGM2OGRkMzgxZTlmMWI3YzM5MWU3MSIsIm4iOiJyYW5kb21pdHkiLCJpZCI6NjIwNTI3fQ==@logs-prod-eu-west-0.grafana.net/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: server-randomity-api
          __path__: /var/log/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
      - labels:
          level: